### ISSUE TITLE
Encrypt results not same as Python or JavaScript Hashids 

### ISSUE THREAD

**Issue by tedmdelacruz** [zakame/hashids.pm#10]
Using the salt `test` and encrypting the integers `1, 2, 3`, both Python and JavaScript versions of the module prints `9mc2s0`, but the Perl version prints `9xt8SB`

In Python:
```
from hashids import Hashids
hashids = Hashids(salt='test')
result = hashids.encode(1, 2, 3)
print(result) # prints 9mc2s0
```

In JavaScript:
```
var Hashids = require('hashids');
var hashids = new Hashids('test');
var result = hashids.encode(1, 2, 3);
console.log(result); // prints 9mc2s0
```

In Perl:
```
use Hashids;
my $hashids = Hashids->new( salt => 'test' );
my $result = $hashids->encrypt(1, 2, 3);
say $result; # prints 9xt8SB
```

EDIT: Realized that this was tested using `v0.08`. Will retest with latest version and change the status of the issue accordingly.

**Comment by tedmdelacruz** [comment]
Confirmed that Perl `Hashids` `1.000002` returns `9mc2s0` which the same as latest stable releases of Python and JavaScript versions of `hashids`

😅

**Comment by zakame** [comment]
Just to remind that this is both on the README and perldoc:

> IMPORTANT: This implementation follows the v1.0.0 API release of hashids.js. An older API of 
> hashids.js (v0.1.4) can be found in Hashids version 0.08 and earlier releases; if you have code that 
> depends on this API version, please use a tool like Carton to pin your Hashids install to the older 
> version.
