### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by mla** [zakame/hashids.pm#14]
```
$ perl -v

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)
```

This triggers an infinite loop:
```
#!/usr/bin/env perl

use strict;
use warnings;
use Hashids;
use bignum;

my $hasher = Hashids->new;
my $hash = $hasher->encode(222);
print "Hash: $hash\n";
```

The problem appears to be the "use bignum" here. In Util->to_alphabet, this is generating a fractional result:

   $num /= @alphabet;

and it goes on indefinitely due to this test: while ( $num != 0 );

Truncating the value fixes it:
$num = int($num / @alphabet);

**Comment by zakame** [comment]
Hi @mla, thanks for the report!  I can confirm reproducing this issue as well as your suggested fix, let me whip up a PR shortly.

**Comment by mla** [comment]
Excellent. Thank you, @zakame!

**Comment by zakame** [comment]
Fix is now published in https://metacpan.org/release/ZAKAME/Hashids-1.001011 :tada:

Thanks again!
