### ISSUE TITLE
Fix {en,de}code_hex() on 32-bit

### ISSUE THREAD

**Issue by zakame** [zakame/hashids.pm#6]
```
ubuntu@ip-10-28-248-157:~/.cpanm/work/1410945139.22296/Hashids-1.000000$ perl '-V:use64.*'
use64bitall='undef';
use64bitint='undef';
ubuntu@ip-10-28-248-157:~/.cpanm/work/1410945139.22296/Hashids-1.000000$ prove -l
t/00_compile.t ... ok
t/01_hashids.t ... 1/9 Integer overflow in hexadecimal number at /home/ubuntu/.cpanm/work/1410945139.22296/Hashids-1.000000/lib/Hashids.pm line 115.
    # Child (encode hex strings) exited without calling finalize()

#   Failed test 'encode hex strings'
#   at /home/ubuntu/.plenv/versions/5.20.0/lib/perl5/5.20.0/Test/Builder.pm line 276.
# Looks like you planned 9 tests but ran 7.
# Looks like you failed 1 test of 7 run.
# Looks like your test exited with 29 just after 7.
t/01_hashids.t ... Dubious, test returned 29 (wstat 7424, 0x1d00)
Failed 3/9 subtests
t/02_subclass.t .. ok

Test Summary Report
-------------------
t/01_hashids.t (Wstat: 7424 Tests: 7 Failed: 1)
  Failed test:  7
  Non-zero exit status: 29
  Parse errors: Bad plan.  You planned 9 tests but ran 7.
Files=3, Tests=12,  0 wallclock secs ( 0.05 usr  0.01 sys +  0.24 cusr  0.02 csys =  0.32 CPU)
Result: FAIL
ubuntu@ip-10-28-248-157:~/.cpanm/work/1410945139.22296/Hashids-1.000000$
```

**Comment by tmorehouse** [comment]
I ran into similar issues as well.  Also, the number being hashed is limited to the size of an int (platform dependant).

I'm working on a modification to the perl library that uses the perl module <code>Math::BigInt</code>, so that arbitrarily large integers can be used.

It requires that each input number passed be converted to a BigInt instance, then performing the modulo division and divisions on those objects.   Should be a simple upgrade to a make it work with any sized number (note that large numbers, if not a BigInt instance already) need to be passed as strings of digits.

**Comment by zakame** [comment]
Nice, thanks for looking into it!  Yeah, I also think `Math::BigInt` is the way to go here, as the PHP implementation has support for using a different math backend, so probably it would be the same situation here.

I'll also try to do some work on this over the weekend, but feel free to hack and submit a pull request!

**Comment by tmorehouse** [comment]
My current solution for handling lard IDs (i.e. 8-byte large unsigned integers), is to take the integer as a string (from my database) and split each digit out into and array var which is then passed to <code>encode().</code>:

    my $hid    = Hashids->new();
    my $bignum = '1234567890123456789012345678901234567890';
    my $hash   = $hid->encode((split(//,$bignum));

But if you need to decode it, you must remember that you will get the result back as an array so you will need to join the result back as a long string.

**Comment by tmorehouse** [comment]
Just thinking, one could probably create a variant of <code>Hashids</code> as a new module called <code>Hashids::BigInt</code>, just in case someone wants the regular integer version, or add a new option to <code>Hashids->new(...)</code> that switches to the BigInt version.

**Comment by tmorehouse** [comment]
Further to the original error regarding the hex conversion, I ran a little test script:

    #! perl -w
    my $str = '123456789abcdef0';
    my @num;
    push @num, '1' . substr $str, 0, 11, '' while $str;
    print join(' ',@num), "\n";
    @num = map {hex} @num;
    print join(' ',@num), "\n";

And got this as the error:

    1123456789ab 1cdef0
    Integer overflow in hexadecimal number at ./testhex.pl line 6.
    Hexadecimal number > 0xffffffff non-portable at ./testhex.pl line 6.
    18843185940907 1892080

Dropping the <code>substr</code> limit from <code>11</code> to <code>7</code> fixes the <code>encode_hex</hex> issue by keeping the length of the hex nums below 8 hex digits (the typical smallest integer size in perl (4 bytes).

This issue is separate from the BigInt issues.

**Comment by tmorehouse** [comment]
I have a rudimentary BigInt version running now, and called it <code>Hashids::BigInt</code>.

I ran a few tests, hasinghte same long numbers through both, compared the resultant hash to see if it was the same result, and also decoded the resultant hashes to see if they returned the original,and ran into some issues on both versions.

Using a random 15 digit string (which doesn't start with a 0):

    IN: 311825411458412
      ORIG: xwlEOq9VWz => 311825411458412 (OK)
       NEW: xwlEOq9VWz => 311825411458412 (OK)
      HASH: Same
    IN: 969238132699443
      ORIG: 0RrvKZ7X8qG => 969238132699443 (OK)
       NEW: 0RrvKZ7X8qG => 969238132699443 (OK)
      HASH: Same
    IN: 539145168911268
      ORIG: NlKmY1QWMN => 539145168911268 (OK)
       NEW: NlKmY1QWMN => 539145168911268 (OK)
      HASH: Same
    IN: 628778643982249
      ORIG: n5Qpm0jg8E7 => 628778643982249 (OK)
       NEW: n5Qpm0jg8E7 => 628778643982249 (OK)
      HASH: Same
    IN: 693379465881534
      ORIG: 1w67L3Nrml3 => 693379465881534 (OK)
       NEW: 1w67L3Nrml3 => 693379465881534 (OK)
      HASH: Same

As you can see both version result in the same hash, and decode back to the origina number fine.

Moving to random 16 digit strings, things start to diverge:

    IN: 6246887887958522
      ORIG: LA7yyM7kg4g => DECODE ERROR (--)
       NEW: LA7yyM7kg4g => 6246887887958522 (OK)
      HASH: Same
    IN: 4913229676696569
      ORIG: PQRxqYZOQV2 => DECODE ERROR (--)
       NEW: O8QwpZyN80Q => DECODE ERROR (--)
      HASH: Different
    IN: 3942321361193234
      ORIG: 1GpOO3WBDBZ => DECODE ERROR (--)
       NEW: 1GpOO3WBDBZ => DECODE ERROR (--)
      HASH: Same
    IN: 1568582615999795
      ORIG: pgmvNOjDqLX => DECODE ERROR (--)
       NEW: pgmvNOjDqLX => DECODE ERROR (--)
      HASH: Same
    IN: 5176811628889687
      ORIG: gkDNp4BDRjr => DECODE ERROR (--)
       NEW: 09oP8zlowk5 => DECODE ERROR (--)
      HASH: Different

In most cases the hash comes out the same (i'm using 32bit Perl btw):. From what I have read, the largest integer number perl can handle (as it will convert integers to floats using 8bytes) is <code>9,007,199,254,740,992</code>, but will start loosing precision as you do arithmetic on it. see http://perldoc.perl.org/perlnumber.html for info

Note that one of the above results shows that the BigInt version (listed as NEW) decoded properly, but others didn't. Not that the number that did work was the largest random number tested... so it doesn't quite make sense yet.  So I am not sure if there is an issue with the original decode logic, or if it is a numerical computation issue.  I've converted most numbers to BigInt, except ones that were only used for indexing strings).

Will investigate a bit more later, and will create a fork and load my revised version into it.

**Comment by tmorehouse** [comment]
I got it working! :-)  I had to change some of the index calculation to use BigInt as well.  Test result:

  INPUT: 7649421916951264562864396399741952972524214892573655927223413516649422
   MASH: LJYq21RROA2E6wqp5JWDmOEg1R3XVroB13KOkK0kY0QA
DECODED: 7649421916951264562864396399741952972524214892573655927223413516649422

  INPUT: 6147522941461294854313999488834441129211836695863148853275953357942316
   MASH: Br3Ej44WVWPvQPkmLQOwRQ5Djq9XxLxLBrVypjP9WGpN
DECODED: 6147522941461294854313999488834441129211836695863148853275953357942316

  INPUT: 1741657141721177458935665683495845879928383253824625939624321828542852
   MASH: qx08lQQvYj42yGnXoKmY9LJX8yM7oV6L4zBzl7WY5yq3
DECODED: 1741657141721177458935665683495845879928383253824625939624321828542852

  INPUT: 8415815178459483164352776943687841922137344988468169168583237592194552
   MASH: qZJWZ7mxMDPr6jyx8g335lVx4oGpN7AGk0RxEk2EYDoD
DECODED: 8415815178459483164352776943687841922137344988468169168583237592194552

  INPUT: 4775464535337356387384493539371255553962613422546123488247143272528857
   MASH: yoxkqyKnnNXEgQ31QJxnVl2mlgL56rqoOYvyL1B5Lz0R
DECODED: 4775464535337356387384493539371255553962613422546123488247143272528857

As you can see, a 70 digit number encodes and decodes perfect now.  Hex now works with arbitrary length hex strings too.

I'll post a fork here very shortly.

**Comment by tmorehouse** [comment]
Fork: https://github.com/tmorehouse/hashids.pm

**Comment by zakame** [comment]
Wow, awesome work!  I'll check it in a bit :+1:

**Comment by tmorehouse** [comment]
The code looks a bit convoluted, as Math::Bigint's function almost always alter the original number object., so you'll see a lot of numbers wrapped in creating a new big int number (so the original doesn't get munged).

And to save on typing, I created a function called _bignum() that is just a shortcut for instantiating a new  BigInt integer.

**Comment by zakame** [comment]
Thanks again for the work!  Bumped the module and it should now hit the CPAN nearest you soon :+1:

**Comment by tmorehouse** [comment]
Excellent. Just did a CPAN install and it it loaded fine.  Didn't have to use <code>force install Hashids</code>, as I had to with the previous version (because of the <code>{en/de}code_hex</code> 32bit int issue).
